### ISSUE TITLE
bad rendering of bug 4378

### ISSUE THREAD

**Issue by jmdyck** [tc39/archives#6]
https://github.com/tc39/archives/blob/master/bugzilla/xml/4378.xml
looks correct, but the rendering at
https://tc39.github.io/archives/bugzilla/4378/
isn't good: the body is just  bullets and colons.

**Comment by IgnoredAmbience** [comment]
Oh, very weird! And somewhat too many entries too. The JSON of the document for passed to the renderer looks ok as well: https://github.com/tc39/archives/blob/master/docs/_bugzilla/4378.md

I should check how the content of the `thetext` field is being processed and rendered in the page template.

**Comment by IgnoredAmbience** [comment]
Conversion of the `long_desc` nodes of the XML into an array doesn't occur when there's only one `long_desc` node. Should be a quick fix.

**Comment by IgnoredAmbience** [comment]
Have pushed up a fix to this. GitHub Pages should rebuild the website and publish it in 15 minutes' time at most.

**Comment by IgnoredAmbience** [comment]
Fix confirmed. https://tc39.github.io/archives/bugzilla/4378/

**Comment by jmdyck** [comment]
Thanks!
