### ISSUE TITLE
Investigate Google Indexing Issues

### ISSUE THREAD

**Issue by IgnoredAmbience** [tc39/archives#7]
For some reason Google isn't indexing https://tc39.github.io/archives/bugzilla/. I have submitted the [relevant sitemap](https://tc39.github.io/archives/sitemap.xml) to be indexed a few times, however nothing seems to yet be appearing in Google searches.

Would anyone be against me registering the archives subdirectory with [Google's Webmaster Tools console](https://www.google.com/webmasters/tools/home) so that I can diagnose any indexing issues? This would involve adding a meta tag with an authorisation code to the index page.

**Comment by IgnoredAmbience** [comment]
Another sensible option might be to create a `robots.txt` file at whichever site is hosted at tc39.github.io (currently https://github.com/tc39/tc39.github.io) in order to point search engines at appropriate `sitemap.xml` files in other subdirectories/repositories. (This probably overlaps significantly with work undertaken by https://github.com/tc39/beta)

**Comment by littledan** [comment]
Both of these actions sound good to me. Use your judgement and go for it.

**Comment by IgnoredAmbience** [comment]
Access to webmaster tools confirmed. Submitted the sitemap url through the console, I'll wait and see if this works.

**Comment by IgnoredAmbience** [comment]
Google seems to have started indexing the site now.
